// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukuyvszuovzucchcwroo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdXl2c3p1b3Z6dWNjaGN3cm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTExMDksImV4cCI6MjA2NDA4NzEwOX0.DcnU95kYJXL4y0S9tvicOYeLzxJ5WWfGOdZifNv321k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);